application:
  name: simple-example-node
  project: getting-started
  cloud_region: aws/us-west-2
  publicly_accessible: true
routers:
- name: main
  routes:
  - application_name: simple-example-node
    paths:
    - /

